// <auto-generated />
using System;
using System.Collections.Generic;
using Florence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Florence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104231136_HealthcareModels")]
    partial class HealthcareModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Florence.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Florence.Models.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpenseReportId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.Property<int>("NurseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseReportId");

                    b.HasIndex("NurseId");

                    b.ToTable("ExpenseItems");
                });

            modelBuilder.Entity("Florence.Models.ExpenseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ExpenseReports");
                });

            modelBuilder.Entity("Florence.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Florence.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("Florence.Models.Nurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Availability24Hours")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvailabilityDailyShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvailabilityNightShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvailabilityWorkInHospital")
                        .HasColumnType("boolean");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoursePlus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExperienceElderly")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExperienceNewborns")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExperienceSnc")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalExperience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Interviewer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSalary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastWorkplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Look")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SkillBadSore")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillBasicCare")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillBedRest")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillBedToilet")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillChemo")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillColostomyBag")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillDressing")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillDrugs")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillFeedingSng")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillFirstAideCourse")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillFolly")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillGastroTube")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillHemoGlucoTest")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillIm")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillIntraDermique")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillIntubation")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillIv")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillPhysiotherapy")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillPulseOxim")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillPulsePressure")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillSmoke")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillSuction")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillTracheotomy")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillTransportation")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkillVaccination")
                        .HasColumnType("boolean");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VacancyOther")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VacancySource")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("Florence.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentPain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyRelationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("FamilyHistory")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("FamilyHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GynecologicalHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InterpreterNeeded")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MedicalConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MentalHealthIssues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicianPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryCarePhysician")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surgeries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vaccinations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Florence.Models.ExpenseItem", b =>
                {
                    b.HasOne("Florence.Models.ExpenseReport", "Report")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Florence.Models.Nurse", "Nurse")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Florence.Models.ExpenseReport", b =>
                {
                    b.HasOne("Florence.Models.Patient", "Patient")
                        .WithMany("ExpenseReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Florence.Models.Invoice", b =>
                {
                    b.HasOne("Florence.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Florence.Models.InvoiceItem", b =>
                {
                    b.HasOne("Florence.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Florence.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Florence.Models.ExpenseReport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Florence.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Florence.Models.Nurse", b =>
                {
                    b.Navigation("ExpenseItems");
                });

            modelBuilder.Entity("Florence.Models.Patient", b =>
                {
                    b.Navigation("ExpenseReports");
                });
#pragma warning restore 612, 618
        }
    }
}
